#!/bin/bash

export BUILD_ID=dontKillMePlease

uname=`uname`

function p() {
    echo -e "\033[32m$1\033[0m"
}

function perr() {
    echo -e "\033[31m$1\033[0m"
}

function pwarn() {
    echo -e "\033[33m$1\033[0m"
}

function pinfo() {
    echo -e "\033[36m$1\033[0m"
}

function get_port() {
  is_use="0"
  if [ "$uname" = "Linux" ];then
    is_use=`netstat -nltp | grep ':'$port' ' | wc -l`
  else
    is_use=`sudo lsof -P -itcp:$port | grep ':'$port' (LISTEN)' | wc -l`
  fi
  while [ $is_use = "1" ]
  do
    let "port+=1"
    if [ "$uname" = "Linux" ];then
      is_use=`netstat -nltp | grep ':'$port' ' | wc -l`
    else
      is_use=`sudo lsof -P -itcp:$port | grep ':'$port' (LISTEN)' | wc -l`
    fi
  done
}

port=3000
get_port
echo 'using port: '$port

errstr="__error__"

filecontent=$(cat package.json)
version=1.0.0
if [ "$uname" = "Linux" ]; then
  version=$(echo $filecontent | jq -r '.version')
fi
echo version=$(echo $version) > /tmp/$feature.profile

err=$errstr
while [ "$err" = "$errstr" ]
do
  err=$(yarn install 1>/dev/null 2>/dev/null || echo $errstr)
  if [ "$err" = "$errstr" ]; then
    echo 'retry install modules...'
    rm -rf node_modules
    sleep 5s
  fi
done
rm -rf dist/$feature/*.*
rm -rf dist/$feature/ftp
export JRJ_FEATURE=$feature
err=$(npm run build 1>/dev/null || echo $errstr)
if [ "$err" = "$errstr" ]; then
  exit 1
fi
err=$(npm run buildserver 1>/dev/null || echo $errstr)
if [ "$err" = "$errstr" ]; then
  exit 1
fi
newfiles=()
ftp -n 117.121.12.155 <<f1 >>/dev/null
quote USER shihuang.piao.ftp.img
quote PASS n6i7&FOy^q
mkdir jrjimg/assets/$feature
mkdir jrjimg/assets/$feature/images
bye
f1

for file in $(ls dist/$feature/*)
do
  if [ -f $file ]; then
    filename=${file##*/}
    status=$(curl -I -w %{http_code} -o /dev/null -s "http://i0.jrjimg.cn/assets/$feature/$filename")
    if [ $status = 404 ]; then
      pinfo "$filename transfered"
      newfiles[${#newfiles[@]}]=$file
      mkdir -p dist/$feature/ftp/
      cp $file dist/$feature/ftp/
    fi
  fi
done

if [ -d dist/$feature/images ]; then
  for file in $(ls dist/$feature/images/*)
  do
    if [ -f $file ]; then
      filename=${file##*/}
      status=$(curl -I -w %{http_code} -o /dev/null -s "http://i0.jrjimg.cn/assets/$feature/images/$filename")
      if [ $status = 404 ]; then
        pinfo "$filename transfered"
        newfiles[${#newfiles[@]}]=$file
        mkdir -p dist/$feature/ftp/images/
        cp $file dist/$feature/ftp/images/
      fi
    fi
  done
fi

if [ ${#newfiles[@]} -gt 0 ]; then
  ftp -n 117.121.12.155 <<f2 >>/dev/null
quote USER shihuang.piao.ftp.img
quote PASS n6i7&FOy^q
prompt
cd jrjimg/assets/$feature/
lcd dist/$feature/ftp/
mput *
bye
f2
  if [ -d dist/$feature/ftp/images ]; then
    ftp -n 117.121.12.155 <<f3 >>/dev/null
quote USER shihuang.piao.ftp.img
quote PASS n6i7&FOy^q
prompt
cd jrjimg/assets/$feature/images/
lcd dist/$feature/ftp/images/
mput *
bye
f3
  fi
  for file in ${newfiles[*]}
  do
    if [ -f $file ]; then
      filename=${file##*/}
      status="404"
      pinfo "waiting for $filename"
      while [ "$status" != "200" ]
      do
        status=$(curl -I -w %{http_code} -o /dev/null -s "http://i0.jrjimg.cn/assets/$feature/$filename")
        wait
        if [ "$status" != "200" ]; then
          sleep 5s
        fi
      done
    fi
  done
  pm2name=$feature_$branch_$port
  err=$(pm2 reload $pm2name 1>/dev/null 2>/dev/null || echo $errstr)
  if [ "$err" = "$errstr" ]; then
    pm2 start -n $pm2name dist/$feature/server/index.js -- $port
  fi
else
  echo 'no files changed'
  exit 1
fi
