#!/bin/bash

export BUILD_ID=dontKillMePlease

function p() {
    echo -e "\033[32m$1\033[0m"
}

function perr() {
    echo -e "\033[31m$1\033[0m"
}

function pwarn() {
    echo -e "\033[33m$1\033[0m"
}

function pinfo() {
    echo -e "\033[36m$1\033[0m"
}

errstr="__error__"

filecontent=$(cat package.json)
#version=$(echo $filecontent | jq -r '.version')
version=1.0.0
echo version=$(echo $version) > /tmp/$feature.profile

err=$errstr
while [ "$err" = "$errstr" ]
do
  err=$(yarn install 1>/dev/null 2>/dev/null || echo $errstr)
  if [ "$err" = "$errstr" ]; then
    echo 'retry install modules...'
    rm -rf node_modules
    sleep 5s
  fi
done
rm -rf dist/$feature/*.*
err=$(npm run build 1>/dev/null || echo $errstr)
if [ "$err" = "$errstr" ]; then
  exit 1
fi
err=$(npm run buildserver 1>/dev/null || echo $errstr)
if [ "$err" = "$errstr" ]; then
  exit 1
fi
newfiles=()
ftp -n 117.121.12.155 <<f1 >>/dev/null
quote USER shihuang.piao.ftp.img
quote PASS n6i7&FOy^q
mkdir jrjimg/assets/$feature
mkdir jrjimg/assets/$feature/images
bye
f1
mkdir -p dist/$feature/ftp/images
for file in $(ls dist/$feature/*)
do
  if [ -f $file ]; then
    filename=${file##*/}
    status=$(curl -I -w %{http_code} -o /dev/null -s "http://i0.jrjimg.cn/assets/$feature/$filename")
    if [ $status = 404 ]; then
      pinfo "$filename transfered"
      newfiles[${#newfiles[@]}]=$file
      cp $file dist/$feature/ftp/
    fi
  fi
done

if [ -d dist/$feature/images ]; then
  for file in $(ls dist/$feature/images/*)
  do
    if [ -f $file ]; then
      filename=${file##*/}
      status=$(curl -I -w %{http_code} -o /dev/null -s "http://i0.jrjimg.cn/assets/$feature/images/$filename")
      if [ $status = 404 ]; then
        pinfo "$filename transfered"
        newfiles[${#newfiles[@]}]=$file
        cp $file dist/$feature/ftp/images/
      fi
    fi
  done
fi

if [ ${#newfiles[@]} -gt 0 ]; then
  ftp -n 117.121.12.155 <<f2 >>/dev/null
quote USER shihuang.piao.ftp.img
quote PASS n6i7&FOy^q
prompt
cd jrjimg/assets/$feature/
lcd dist/$feature/ftp/
mput *
cd jrjimg/assets/$feature/images/
lcd images/
mput *
bye
f2
  for file in ${newfiles[*]}
  do
    if [ -f $file ]; then
      filename=${file##*/}
      status="404"
      pinfo "waiting for $filename"
      while [ "$status" != "200" ]
      do
        status=$(curl -I -w %{http_code} -o /dev/null -s "http://i0.jrjimg.cn/assets/$feature/$filename")
        wait
        if [ "$status" != "200" ]; then
          sleep 5s
        fi
      done
    fi
  done

  err=$(pm2 reload $feature 1>/dev/null 2>/dev/null || echo $errstr)
  if [ "$err" = "$errstr" ]; then
    pm2 start -n $feature dist/$feature/server/index.js
  fi
else
  echo 'no files changed'
  exit 1
fi
