#!/bin/sh

cd "$(cd "$(dirname "$0")"; pwd -P)/../../"
files=($(git status -bs | grep '^[MAU]' | awk '{print $2}'))
if [ ${#files[@]} -gt 0 ]; then
  for file in ${files[*]}
  do
    str=$file
    IFS=.
    ary=($file)
    IFS=
    echo 2,$file
    if [ "${ary[1]}" = "js" ]; then
      coffee beautifiers/beautify.coffee $file
    fi
  done
  git add .
fi
exit 0
